# -*- coding: utf-8 -*-
"""Plant_disease.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uw6GQ9M54wLKscRhAhLv00Jdr3fqn-7B
"""

import random
random.seed(0)

import numpy as np
np.random.seed(0)

import tensorflow as tf
tf.random.set_seed(0)

import os
import json
from zipfile import ZipFile
from PIL import Image

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras import layers, models

!pip install kaggle

kaggle_credentials = json.load(open('kaggle.json'))

os.environ['KAGGLE_USERNAME'] = kaggle_credentials["username"]
os.environ['KAGGLE_KEY'] = kaggle_credentials["key"]

!kaggle datasets download -d emmarex/plantdisease

!ls

with ZipFile("plantdisease.zip", "r") as zip_p:
  zip_p.extractall()

print(os.listdir("plantvillage"))

image_path = '/content/PlantVillage/Pepper__bell___Bacterial_spot/0022d6b7-d47c-4ee2-ae9a-392a53f48647___JR_B.Spot 8964.JPG'

img = mpimg.imread(image_path)
print(img.shape)

plt.imshow(img)
plt.axis('off')
plt.show()

img_size = 224
batch_size = 32

data_gen = ImageDataGenerator(
    rescale=1./255,
    validation_split=0.2
)

train_generator = data_gen.flow_from_directory(
    '/content/PlantVillage',
    target_size=(img_size, img_size),
    batch_size=batch_size,
    subset='training',
    class_mode = 'categorical'
)

validation_generator = data_gen.flow_from_directory(
    '/content/PlantVillage',
    target_size=(img_size, img_size),
    batch_size=batch_size,
    subset='validation',
    class_mode = 'categorical'
)

model = models.Sequential()

model.add(layers.Conv2D(32,(3,3), activation='relu', input_shape=(img_size, img_size, 3)))
model.add(layers.MaxPooling2D((2,2)))

model.add(layers.Conv2D(64,(3,3), activation='relu'))
model.add(layers.MaxPooling2D((2,2)))

model.add(layers.Flatten())
model.add(layers.Dense(256, activation='relu'))
model.add(layers.Dense(train_generator.num_classes, activation='softmax'))

model.summary()

model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    train_generator,
    steps_per_epoch=train_generator.samples // batch_size,
    epochs=5,
    validation_data=validation_generator,
    validation_steps=validation_generator.samples // batch_size
)

val_loss, val_accuracy = model.evaluate(validation_generator, steps=validation_generator.samples // batch_size)
print(f"Validation Loss: {val_loss:.4f}")
print(f"Validation Accuracy: {val_accuracy:.4f}")

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Model Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend(['Train', 'Test'],loc='lower right')
plt.show()

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Model Accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.legend(['Train', 'Test'],loc='lower right')
plt.show()

def load_and_preprocess_image(image_path, target_size=(224,224)):
    img = Image.open(image_path)
    img = img.resize(target_size)
    img_array = np.array(img)
    img_array = np.expand_dims(img_array, axis=0)
    img_array = img_array.astype('float32')/255
    return img_array

def predict_image_class(model, image_path, class_indices):
  preprocessed_image = load_and_preprocess_image(image_path)
  predictions = model.predict(preprocessed_image)
  predicted_class_index = np.argmax(predictions)
  predicted_class_name = class_indices[predicted_class_index]
  return predicted_class_name

class_indices = {v: k for k, v in train_generator.class_indices.items()}

class_indices

json.dump(class_indices, open('class_indices.json', 'w'))

image_path = '/content/plant_dis1.jpg'
predicted_class_name = predict_image_class(model, image_path, class_indices)
print(f"The predicted class for the image is: {predicted_class_name}")

##model.save('drive/MyDrive/trained_models/plant_disease_prediction_model.h5')